config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque', as: :resque

  resources :projects, shallow: true do
    resources :scenarios, except: :index do
      member do
        patch :move_up
        patch :move_down
      end

      resources :steps, only: %i[index show create edit update destroy]

      resources :build_histories, only: %i[index show create]
    end
  end

  resource :system_setting, except: :destroy do
    get :download_node
    get :grid
  end

  # 将来、各種コントローラのアクションがAPIとの互換性を維持できなくなった際は、
  # 旧仕様用のコントローラを「app/controllers/api/<旧版>/」以下に定義する。
  scope :api do
    scope :v1 do
      resources :projects, shallow: true, only: :show do
        resources :scenarios, only: [] do
          resources :build_histories, only: %i[show create]
        end
      end
    end
  end

  root to: 'top#index'
end

app/models/system_setting.rb
class SystemSetting < ActiveRecord::Base

  def save_and_generate_node!
    save!
    JobUtils.add_job(GenerateSeleniumNodeJob)
  end

end

app/controllers/system_settings_controller.rb
class SystemSettingsController < ApplicationController
  include HaenawaConst

  def show
    @system_setting = SystemSetting.first
    redirect_to :action => 'new' unless @system_setting.present?
  end

  def grid
    unless SystemSetting.first.selenium_host.present?
      render :nothing => true and return
    end

    begin
      conn = Faraday.new(:url => "http://#{SystemSetting.first.selenium_host}:4444") do |faraday|
       faraday.request :url_encoded
       faraday.adapter Faraday.default_adapter
      end

      response = conn.get('/grid/console')
      @nodes = Nokogiri::HTML(response.body).css('div.proxy')
      render :partial => 'grid'
    rescue => e
      @message = e.message
      render :partial => 'hub_connection_error'
    end
  end

  def download_node
    send_file File.join(SELENIUM_DIR, 'selenium-2.53.zip')
  end

  def new
    @system_setting = SystemSetting.new
  end

  def create
    @system_setting = SystemSetting.new(system_setting_params)
    
    @system_setting.transaction do
      @system_setting.save_and_generate_node!
    end
    
    redirect_to @system_setting
  end
  
  def edit
    @system_setting = SystemSetting.first
  end

  def update
    @system_setting = SystemSetting.first
    @system_setting.attributes = system_setting_params
    
    @system_setting.transaction do
      @system_setting.save_and_generate_node!
    end
    
    redirect_to :action => 'show'
  end

  private

  def system_setting_params
    permitted = [:selenium_host]
    
    ret = params.require(:system_setting)

    case action_name
    when 'create', 'update'
      ret = ret.permit(*permitted)
    end
    
    ret
  end
end

app/views/system_settings/_form.html.erb
<div class="well bs-component">
  <%= form_for @system_setting, :url => system_setting_path, :html => {:role => 'form', :class => 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= f.label :selenium_host, :class => 'col-md-2 control-label' %>
      <%= f.text_field :selenium_host, :class => 'col-md-10 form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit :class => 'btn btn-primary btn-raised pull-right' %>
    </div>
  <% end %>
</div>

app/views/system_settings/_grid.html.erb
<% if @nodes.empty? %>
  <div class="alert alert-danger" role="alert">
    <span>接続しているノードはありません。</span>
  </div>
<% end %>

<div class="list-group">
  <% @nodes.each_with_index do |node, i| %>
    <div class="list-group-item">
      <div class="row-action-primary">ノード #<%= i + 1 %></div>
      <div class="row-content">
        <div><%= node.css('.proxyname').text %></div>
        <div><%= node.css('.proxyid').text %></div>
        <div>
          <ul>
            <% node.css('[type="browsers"] p:not(.protocol)').each do |browser| %>
              <% if browser.css('img').present? %>
                <% detail = browser.css('img').first['title'].strip[1..-2].split(',').map(&:strip) %>
                <li>
                  <% browser_name = detail.map{|d| d.split('=') }.find{|d| d[0] == 'browserName' }[1].gsub(' ', '_') %>
                  <%= image_tag("#{browser_name}.png", :title => browser_name ) %>
                  <%= detail %>
                </li>
              <% else %>
                <% browser.css('a').present? ?
                      browser.css('a').first.attr('title') :
                      '??' %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/system_settings/_hub_connection_error.html.erb
<div class="alert alert-danger" role="alert">
  <%= html_line_break(@message) %>
</div>

app/views/system_settings/edit.html.erb
<%= link_to '戻る', system_setting_path, :class => 'btn btn-default btn-raised' %>

<%= render 'form' %>

app/views/system_settings/new.html.erb
<%= render 'form' %>

app/views/system_settings/show.html.erb
<% if @system_setting.new_record? %>
  <%= link_to '編集', new_system_setting_path, :class => 'btn btn-info' %>
<% else %>
  <%= link_to '編集', edit_system_setting_path, :class => 'btn btn-info' %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table">
      <tr class="row">
        <th class="col-md-2">
          <%= SystemSetting.human_attribute_name :selenium_host %>
        </th>
        <td class="col-md-7">
          <%= @system_setting.selenium_host %>
        </td>
        <td class="col-md-3">
          <%= link_to 'ノード用パッケージ', {:action => 'download_node'}, :data => {turbolinks: false} %>
        </td>
      </tr>
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $.get('<%= url_for :action => 'grid' %>', {format: 'html'}, function(html) {
      $('#selenium_grid').html(html);
    });
  });
</script>
<div>
  <div id="selenium_grid" class="col-md-12 grid">
    <%= image_tag('loading.gif') %>
  </div>
</div>