config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque', as: :resque

  resources :projects, shallow: true do
    resources :scenarios, except: :index do
      member do
        patch :move_up
        patch :move_down
      end

      resources :steps, only: %i[index show create edit update destroy]

      resources :build_histories, only: %i[index show create]
    end
  end

  resource :system_setting, except: :destroy do
    get :download_node
    get :grid
  end

  # 将来、各種コントローラのアクションがAPIとの互換性を維持できなくなった際は、
  # 旧仕様用のコントローラを「app/controllers/api/<旧版>/」以下に定義する。
  scope :api do
    scope :v1 do
      resources :projects, shallow: true, only: :show do
        resources :scenarios, only: [] do
          resources :build_histories, only: %i[show create]
        end
      end
    end
  end

  root to: 'top#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true

  include RedmineAware

  has_many :scenarios, -> {where(deleted: false).order(:scenario_no)}

  def masked_redmine_api_key
    if redmine_api_key.present?
      '*' * 32
    else
      nil
    end
  end

  def build_dir
    File.join(STORE_BASE_DIR, id.to_s)
  end

  def feature_dir
    File.join(build_dir, 'features')
  end

  def support_dir
    File.join(feature_dir, 'support')
  end

  def save_and_generate_support_env!
    save!
    JobUtils.add_job(GenerateSupportEnvJob, :project_id => id)
  end

  def create_issue(params)
    redmine.create_issue(params)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.my_projects.page(params[:page]).per(10)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    begin
      @project.transaction do
        @project.save_and_generate_support_env!
      end

      redirect_to @project
    rescue ActiveRecord::RecordInvalid => e
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.attributes = project_params

    begin
      @project.transaction do
        @project.save_and_generate_support_env!
      end

      redirect_to @project
    rescue ActiveRecord::RecordInvalid => e
      render :edit
    rescue ActiveRecord::StaleObjectError => e
      @project.errors[:base] << I18n.t('error.messages.stale')
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.attributes = {:deleted => true}

    @project.transaction do
      @project.save!
    end

    redirect_to action: :index
  end

  private

  def default_url_options
    {
      :page => params[:page]
    }
  end

  def project_params
    permitted = [:name, :lock_version, :use_redmine, :redmine_host, :redmine_api_key, :redmine_identifier, :default_build_sequence_code]

    params.require(:project).permit(*permitted)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= render_error_messages @project %>

<div class="well bs-component">
  <%= form_for @project, :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.hidden_field :lock_version %>

    <div class="form-group">
      <%= f.label :name, :class => 'col-md-2 control-label' %>
      <%= f.text_field :name, :class => 'col-md-10 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :default_build_sequence_code, t('.default_build_sequence_code').html_safe, :class => 'col-md-2 control-label' %>
      <%= f.text_field :default_build_sequence_code, :class => 'col-md-10 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :use_redmine, :class => 'col-md-2 control-label' %>
      <%= render 'redmine_fields' %>
    </div>
    <div class="form-group">
      <%= f.submit :class => 'btn btn-primary btn-raised pull-right' %>
    </div>
  <% end %>
</div>

app/views/projects/_redmine.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @project.use_redmine? ? '連携する' : '連携しない' %>
  </div>
  <div class="panel-body">
    <table class="table">
      <tr class="row">
        <th class="col-md-3">
          <%= Project.human_attribute_name :redmine_host %>
        </th>
        <td class="col-md-9">
          <%= @project.redmine_host %>
        </td>
      </tr>
      <tr class="row">
        <th class="col-md-3">
          <%= Project.human_attribute_name :redmine_api_key %>
        </th>
        <td class="col-md-9">
          <%= @project.masked_redmine_api_key %>
        </td>
      </tr>
      <tr class="row">
        <th class="col-md-3">
          <%= Project.human_attribute_name :redmine_identifier %>
        </th>
        <td class="col-md-9">
          <%= @project.redmine_identifier %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/projects/_redmine_fields.html.erb
<%= fields_for @project do |f| %>
  <div class="panel panel-default col-md-offset-2">
    <div class="panel-heading">
      <%= material_check_box f, '連携する', :use_redmine %>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :redmine_host, :class => 'col-md-3 control-label' %>
        <%= f.text_field :redmine_host, :class => 'col-md-9 form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :redmine_api_key, :class => 'col-md-3 control-label' %>
        <%= f.text_field :redmine_api_key, :class => 'col-md-9 form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :redmine_identifier, :class => 'col-md-3 control-label' %>
        <%= f.text_field :redmine_identifier, :class => 'col-md-9 form-control' %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= link_to '戻る', project_path(@project), :class => 'btn btn-default btn-raised' %>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= link_to '新しいプロジェクトを追加', new_project_path, :class => 'btn btn-raised btn-info' %>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><%= Project.human_attribute_name :name %></th>
          <th><%= Project.human_attribute_name :use_redmine %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |p| %>
          <tr>
            <td><%= link_to p.name, project_path(p) %></td>
            <td><%= p.use_redmine? ? '連携する' : '連携しない' %></td>
            <td><%= link_to p.redmine_project_url, p.redmine_project_url, :target => '_blank', :data => {:no_turbolink => true} if p.use_redmine? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to '一覧に戻る', projects_path, class: 'btn btn-default btn-raised' %>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <h3><%= @project.name %></h3>
</div>

<%= link_to '編集', edit_project_path(@project), :class => 'btn btn-raised btn-info' %>
<%= link_to '削除', project_path(@project), :method => 'delete', :class => 'btn btn-raised btn-danger',
      :data => {:confirm => "#{@project.name} を削除します。よろしいですか？"} %>
<%= link_to '一覧に戻る', projects_path, class: 'btn btn-raised' %>

<div class="project">
  <div class="panel panel-default">
    <div class="panel-heading">
      プロジェクト
    </div>
    <div class="panel-body">
      <table class="table">
        <tr class="row">
          <th class="col-md-2">
            <%= Project.human_attribute_name :default_build_sequence_code %>
          </th>
          <td class="col-md-10">
            <%= @project.default_build_sequence_code %>
          </td>
        </tr>
        <tr class="row">
          <th class="col-md-2">
            <%= Project.human_attribute_name :use_redmine %>
          </th>
          <td class="col-md-10">
            <%= render 'redmine' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    シナリオ
  </div>
  <div class="panel-body">
    <%= link_to('新しいシナリオを追加', new_project_scenario_path(@project), class: 'btn btn-raised btn-info') %>
    <table class="table">
      <thead>
        <tr>
          <th><%= Scenario.human_attribute_name :scenario_no %></th>
          <th><%= Scenario.human_attribute_name :name %></th>
          <th><%= Scenario.human_attribute_name :base_url %></th>
          <th><%= t('.build_count') %></th>
          <th><%= t('views.scenarios.show.latest_build_result') %></th>
          <th><%= t('.operations') %></th>
        </tr>
      </thead>
      <tbody>
        <% @project.scenarios.each do |s| %>
          <tr>
            <td><%= s.scenario_no %></td>
            <td><%= link_to s.name, s %></td>
            <td><%= s.base_url %></td>
            <td><%= s.build_histories.count %></td>
            <td>
              <%=
                if s.build_histories.present?
                  branches = s.build_histories.group_by(&:build_no).values.last
                  if BuildHistory.all_finished?(branches)
                    result = BuildHistory.result_string(branches)
                    finished_at = BuildHistory.finished_at_string(branches)
                    build_no = branches.first.build_no
                    "##{build_no} #{finished_at} (#{result})"
                  end
                end
              %>
            </td>
            <td>
              <%= link_to content_tag(:span, nil, class: 'fas fa-arrow-down', title:  t('.move_scenario_down')), move_down_scenario_path(s), method: :patch, remote: true, style: "visibility:#{s.last? ? 'hidden' : 'visible'}" %>
              <%= link_to content_tag(:span, nil, class: 'fas fa-arrow-up', title:  t('.move_scenario_up')),  move_up_scenario_path(s), method: :patch, remote: true, style: "visibility:#{s.first? ? 'hidden' : 'visible'}" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>