config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque', as: :resque

  resources :projects, shallow: true do
    resources :scenarios, except: :index do
      member do
        patch :move_up
        patch :move_down
      end

      resources :steps, only: %i[index show create edit update destroy]

      resources :build_histories, only: %i[index show create]
    end
  end

  resource :system_setting, except: :destroy do
    get :download_node
    get :grid
  end

  # 将来、各種コントローラのアクションがAPIとの互換性を維持できなくなった際は、
  # 旧仕様用のコントローラを「app/controllers/api/<旧版>/」以下に定義する。
  scope :api do
    scope :v1 do
      resources :projects, shallow: true, only: :show do
        resources :scenarios, only: [] do
          resources :build_histories, only: %i[show create]
        end
      end
    end
  end

  root to: 'top#index'
end

app/models/step.rb
require 'active_support/core_ext/digest/uuid'

class Step < ActiveRecord::Base
  include ::Encryptor

  belongs_to :steppable, polymorphic: true, inverse_of: 'steps'

  acts_as_list scope: :steppable, column: :step_no

  after_initialize :set_default_values


  # .sideファイルを読み込む段階ではバリデーションをスキップする。
  validates :command, on: :update, :inclusion => { in: Haenawa::Command::COMMAND_NAMES }
  validate(on: :update) { step_command.validate }

  class << self
    def default_attrs
      { command: 'click', target: 'css=body' }
    end
  end

  def targets
    ActiveSupport::JSON.decode(raw_targets)
  end

  def targets=(o)
    self.raw_targets = ActiveSupport::JSON.encode(o)
  end

  def step_command
    @step_command ||= Haenawa::Command.create_from_step(self)
  end

  # .sideファイルの内容へ変換する。
  def to_side_file_content
    {
      id: uuid,
      comment: comment,
      command: command,
      target: target,
      targets: targets,
      value: value,
    }
  end

  def command_names
    # .sideファイルに未対応のコマンドが入っていることはあり得るので
    # COMMAND_NAMESに含まれていないコマンドのステップが生成される可能性がある。
    # この可能性に備えて本ステップのコマンドを戻り値の配列に追加する。
    (Haenawa::Command::COMMAND_NAMES + [command]).uniq
  end

  def should_mask?
    case command
    when 'type'
      target.include?('password')
    else
      false
    end
  end

  def masked_value
    if value.present?
      should_mask? ? '********' : value
    elsif encrypted_value.present?
      '********'
    end
  end

  def encrypt
    if value.present?
      should_mask? ? encrypt_and_sign(value) : value
    end
  end

  def decrypt
    if value.present?
      should_mask? ? decrypt_and_verify(value) : value
    end
  end

  private

  def uuid
    namespace = 'HaenawaStep'
    name = [comment, command, target, raw_targets].join
    Digest::UUID.uuid_v5(namespace, name)
  end

  def set_default_values
    # MySQLのTEXT型にはデフォルト値が付与できないため、
    # モデルでデフォルト値を与える。
    if !target
      self.target = ''
    end
    if !value
      self.value = ''
    end
    if !comment
      self.comment = ''
    end
    if !raw_targets.present?
      self.raw_targets = '[]'
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :find_scenario, only: %i[index create]
  before_action :find_step, except: %i[index create]
  before_action :set_scenario, except: %i[index create]
  before_action :set_project

  def index
  end

  def show
    image_path = @step.steppable.screenshot_path_for(@step.step_no)
    if File.exist?(image_path)
      filename = "img-#{@step.steppable.id}-#{'%02d' % @step.step_no}.png"
      send_file(image_path, filename: filename, disposition: 'inline')
    else
      send_file File.join('app', 'assets', 'images', 'loading.gif')
    end
  end

  def create
    step_attrs = Step.default_attrs.merge(step_no: params[:step_no])
    step = @scenario.steps.build(step_attrs)
    ActiveRecord::Base.transaction do
      step.save!
      @scenario.touch
    end
    render :index
  end

  def edit
  end

  def update
    @step.attributes = step_params
    begin
      @step.save!
      @scenario.touch
      redirect_to @scenario
    rescue ActiveRecord::RecordInvalid
      render :edit
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      @step.remove_from_list
      @step.update_attribute(:deleted, true)
      @scenario.touch
    end
    render :index
  end

  private

  def step_params
    params.require(:step).permit(:command, :target, :value, :comment)
  end

  def find_scenario
    @scenario = Scenario.find(params[:scenario_id])
  end

  def find_step
    @step = Step.find(params[:id])
  end

  def set_scenario
    @scenario = @step.steppable.scenario
  end

  def set_project
    @project = @scenario.project
  end
end

app/helpers/steps_helper.rb
module StepsHelper
  def description_div(command, type, visible)
    description = begin
      key = "views.steps.edit.descriptions.#{type}.#{command}"
      default_key = 'views.steps.edit.descriptions.unsupported_command'
      I18n.t(key, default: default_key).html_safe
    end

    explanation = begin
      key = "views.steps.edit.explanations.#{type}.#{command}"
      I18n.t(key, default: '').html_safe
    end

    attrs = {
      id: "#{command}-#{type}-description",
      class: 'description'
    }

    if !visible
      attrs[:style] = 'display:none;'
    end

    explanation_id = "#{command}-#{type}-explanation"

    explanation_toggle = if explanation.blank?
      ''
    else
      toggle_text = I18n.t('views.steps.edit.toggle_explanation')
      content_tag(:a, toggle_text, data: { toggle: 'collapse' }, href: "##{explanation_id}")
    end

    explanation_div = if explanation.blank?
      ''
    else
      content_tag(:div, explanation, id: explanation_id, class: 'well collapse')
    end

    description_span = content_tag(:span, description)

    content_tag(:div, attrs) do
      content_tag(:p, description_span + explanation_toggle) + explanation_div
    end
  end
end

app/views/steps/_index.html.erb
<script>
  new haenawa.ProgressUpdater('#steps');
</script>

<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= Step.model_name.human %></strong>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= Step.human_attribute_name :step_no %></th>
          <th><%= Step.human_attribute_name :command %></th>
          <th><%= Step.human_attribute_name :target %></th>
          <th><%= Step.human_attribute_name :value %></th>
          <% devices.keys.each do |device| %>
            <th><%= device_icon(device) %></th>
          <% end %>
          <th><%= t('.operations') %></th>
        </tr>
      </thead>
      <tbody>
        <% if @scenario.steps.empty? %>
          <tr>
            <td colspan="<%= devices.length + 5 %>"><%= progress_indicator_image(scenario_steps_url(@scenario)) %></td>
          </tr>
        <% else %>
          <% @scenario.steps.each do |step| %>
            <!-- Step#id: <%= step.id %> -->
            <tr<%= title_attr_from_comment(step) %>>
              <td style="word-break: break-all;"><%= step.step_no %></td>
              <td style="word-break: break-all;"><%= step.command %></td>
              <td style="word-break: break-all;"><%= step.target %></td>
              <td style="word-break: break-all;"><%= step.masked_value %></td>
              <% if @scenario.latest_build_branches.none? || @scenario.latest_build_stale? %>
                <% devices.length.times do %>
                  <td></td>
                <% end %>
              <% else %>
                <% devices.keys.each do |device| %>
                  <td><%= latest_build_result_icon(@scenario, device, step) %></td>
                <% end %>
              <% end %>
              <td style="white-space: nowrap;">
                <%= link_to content_tag(:span, nil, class: 'fas fa-plus', title: t('.add')), scenario_steps_path(@scenario, step_no: step.step_no + 1), method: :post, remote: true %>
                <%= link_to content_tag(:span, nil, class: 'fas fa-minus', title: t('.remove')), step_path(step), method: :delete, remote: true %>
                <%= link_to content_tag(:span, nil, class: 'fas fa-edit', title:  t('.edit')), edit_step_path(step) %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/steps/edit.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(function($) {
    var $select = $('#step_command');

    function toggleDescriptionVisibility() {
      $('div.description').hide();
      var command = $select.val();
      $('#' + command + '-command-description').show();
      $('#' + command + '-target-description').show();
      $('#' + command + '-value-description').show();
    }

    $select.change(toggleDescriptionVisibility);
  });
</script>
<%= link_to '戻る', @scenario, class: 'btn btn-default btn-raised' %>
<%= render_error_messages @step %>
<div class="well bs-component">
<%= form_for @step, html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :command, :class => 'col-md-2 control-label' %>
    <%= f.select :command, options_for_select(@step.command_names, @step.command), {}, class: 'col-md-10 form-control' %>
    <div class="col-md-2"></div>
    <div class="col-md-8 help-block">
      <% @step.command_names.each do |command| %>
        <%= description_div(command, 'command', @step.command == command) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :target, :class => 'col-md-2 control-label' %>
    <samp>
      <%= f.text_field :target, class: 'col-md-10 form-control' %>
    </samp>
    <div class="col-md-2"></div>
    <div class="col-md-8 help-block">
      <% @step.command_names.each do |command| %>
        <%= description_div(command, 'target', @step.command == command) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'col-md-2 control-label' %>
    <samp>
      <%= f.text_area :value, class: 'col-md-10 form-control', rows: 10 %>
    </samp>
    <div class="col-md-2"></div>
    <div class="col-md-8 help-block">
      <% @step.command_names.each do |command| %>
        <%= description_div(command, 'value', @step.command == command) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comment, class: 'col-md-2 control-label' %>
    <samp>
      <%= f.text_area :comment, class: 'col-md-10 form-control', rows: 10 %>
    </samp>
    <div class="col-md-2"></div>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary btn-raised pull-right' %>
  </div>
<% end %>
</div>

app/views/steps/index.js.erb
$("#steps").html("<%= j(render partial: 'index') %>");