config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque', as: :resque

  resources :projects, shallow: true do
    resources :scenarios, except: :index do
      member do
        patch :move_up
        patch :move_down
      end

      resources :steps, only: %i[index show create edit update destroy]

      resources :build_histories, only: %i[index show create]
    end
  end

  resource :system_setting, except: :destroy do
    get :download_node
    get :grid
  end

  # 将来、各種コントローラのアクションがAPIとの互換性を維持できなくなった際は、
  # 旧仕様用のコントローラを「app/controllers/api/<旧版>/」以下に定義する。
  scope :api do
    scope :v1 do
      resources :projects, shallow: true, only: :show do
        resources :scenarios, only: [] do
          resources :build_histories, only: %i[show create]
        end
      end
    end
  end

  root to: 'top#index'
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :project

  acts_as_list scope: 'project_id = #{project_id} AND deleted = false',
               column: :scenario_no

  validates :name, presence: true
  validates :file, presence: true

  mount_uploader :file, ScenarioUploader

  include Steppable

  has_many :build_histories
  accepts_nested_attributes_for :build_histories

  alias_method :scenario, :itself

  def base_url
    parsed_file.base_url
  end

  def app_host
    base_url.split('://')[1].to_s.split('/')[0]
  end

  def app_port
    ret = base_url.split('://')[2].to_s.split('/')[0]
    if ret.blank?
      ret = '80' if base_url.start_with?('http://')
      ret = '443' if base_url.start_with?('https://')
    end
    ret
  end

  # 最新のビルドの番号（build_no）を取得する。
  # 「ビルド」を表すのはあくまでこのbuild_no。
  def latest_build_no
    @latest_build_no ||= build_histories.maximum(:build_no)
  end

  # .sideファイルの内容へ変換する。
  def to_side_file_content
    result_commands = steps.map(&:to_side_file_content)
    result = JSON.parse(file.file.read, symbolize_names: true)
    result[:tests][0][:commands] = result_commands
    result
  end

  # 特定のビルドのBuildHistoryレコードを取得する。
  # 特定のビルドに所属するBuildHistoryレコードはそのビルドの「ブランチ」と言う。
  # ブランチは対象デバイス毎に作られる。
  def build_branches(build_no)
    build_histories.where(build_no: build_no)
  end

  # 最新のビルドのブランチを取得する。
  def latest_build_branches
    @latest_build_branches ||= build_branches(latest_build_no)
  end

  # 最新のビルドのブランチの内、特定の対象デバイスのブランチを取得する。
  def latest_build_branch(device)
    latest_build_branches.where(device: device).first
  end

  # 最新のビルドのブランチの内、完了したブランチを取得する。
  def latest_build_finished_branches
    @latest_build_finished_branches ||= latest_build_branches.where.not(finished_at: nil)
  end

  # 最新のビルドのブランチの内、ステップ情報がシナリオの状態から乖離したものを取得する。
  def latest_build_stale_branches
    @latest_build_stale_branches ||= latest_build_branches.where("created_at < ?", updated_at)
  end

  def latest_build_stale?
    @latest_build_stale ||= latest_build_stale_branches.any?
  end

  def feature_file
    File.join(project.feature_dir, "scenario_#{id}.feature")
  end

  def steps_file
    File.join(project.feature_dir, 'step_definitions', "scenario_#{id}.rb")
  end

  def test_result_dir
    File.join(project.build_dir, 'test', "scenario_#{id}")
  end

  def parsed_file
    @parsed_file ||= Haenawa::SeleniumScriptParser.run(file)
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  include SetBuildHistories

  before_action :find_project, only: %i[new create]
  before_action :find_scenario, except: %i[new create]
  before_action :set_project, except: %i[new create]

  def show
    respond_to do |format|
      format.html do
        set_build_histories
      end
      format.side do
        # 旧バージョンのSelenium IDE出力ファイルは考慮していない。

        send_data(JSON.pretty_generate(@scenario.to_side_file_content), filename: @scenario.original_filename, disposition: 'attachment')
      end
    end
  end

  def new
    @scenario = @project.scenarios.build
  end

  def create
    @scenario = @project.scenarios.build(scenario_params)
    begin
      @scenario.save!
      JobUtils.add_job(CreateStepsJob, scenario_id: @scenario.id)
      redirect_to @scenario
    rescue ActiveRecord::RecordInvalid => e
      render :new
    end
  end

  def edit
  end

  def update
    @scenario.attributes = scenario_params
    begin
      @scenario.save!
      redirect_to @scenario
    rescue ActiveRecord::RecordInvalid => e
      render :edit
    end
  end

  def destroy
    @scenario.attributes = {:deleted => true}

    @scenario.transaction do
      @scenario.remove_from_list
      @scenario.save!
    end

    redirect_to @project
  end

  def move_up
    @scenario.move_higher
    redirect_to @project
  end

  def move_down
    @scenario.move_lower
    redirect_to @project
  end

  private

  def scenario_params
    permitted = [:name]
    ret = params.require(:scenario)

    case action_name
    when 'create'
      ret = ret.permit(permitted, :project_id, :file)
    when 'update'
      ret = ret.permit(permitted)
    end

    ret
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_scenario
    @scenario = Scenario.find(params[:id])
  end

  def set_project
    @project = @scenario.project
  end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
  # シナリオ実行用のデバイス
  DEVICES = {
    # デバイスの識別子: デフォルトでチェックを入れるかどうかのフラグ
    ie: false,
    chrome: false,
    headless_chrome: true,
    firefox: false,
    iphone6: false,
    ipad_pro: false,
    android: ENV['SHOW_ANDROID'],
  }.compact.freeze

  # デバイスアイコン用のCSSクラス
  # 当該するアイコンについては https://fontawesome.com/icons を参照。
  ICON_CLASSES = {
    ie: "fab fa-internet-explorer",
    chrome: "fab fa-chrome",
    headless_chrome: "fab fa-chrome",
    firefox: "fab fa-firefox",
    iphone6: "fas fa-mobile-alt",
    ipad_pro: "fas fa-tablet-alt",
    android: "fab fa-android",
  }.freeze

  def devices
    DEVICES
  end

  def device_title(device)
    I18n.t(device, scope: 'views.scenarios.show.device.select')
  end

  def device_icon(device)
    content_tag(:span, nil, class: ICON_CLASSES[device.to_sym], title: device_title(device))
  end

  # 特定のデバイス上の特定ステップの実行結果（成功、失敗、未実施）を表すアイコンを返す。
  def latest_build_result_icon(scenario, device, step)
    if scenario.latest_build_stale?
      return '' # ビルドのステップ情報がシナリオの状態から乖離した場合。
    end

    branch = scenario.latest_build_branch(device) # BuildHistory

    if branch.nil?
      return '' # まだビルドしたことが無い場合。
    end

    step_status = branch.step_status(step.step_no)&.to_sym

    # ブランチの結果での判定
    if branch.pending?
      css_class = 'fas fa-hourglass-half'
    elsif branch.passed?
      css_class = 'fas fa-check' # ブランチの成功 == 全てのステップの成功
    else
      # ステップの結果で判定
      css_class = {
        passed: 'fas fa-check',
        failed: 'fas fa-times',
        skipped: 'fas fa-minus'
      }[step_status]
    end

    if [:passed, :failed].include?(step_status)
      link_to build_history_path(branch, anchor: "step_no=#{step.step_no}") do
        content_tag(:span, nil, class: css_class)
      end
    else
      content_tag(:span, nil, class: css_class)
    end
  end

  def progress_indicator_image(url)
    opts = {
      class: 'loading',
      # data-urlはhaenawa.ProgressUpdaterの進捗更新処理で使う。
      data: {
        url: url
      }
    }
    image_tag('loading.gif', opts)
  end
end

app/views/scenarios/edit.html.erb
<%= link_to '戻る', scenario_path(@scenario), :class => 'btn btn-default btn-raised' %>
<%= render_error_messages @scenario %>
<div class="well bs-component">
<%= form_for @scenario, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'col-md-2 control-label' %>
    <%= f.text_field :name, :class => 'col-md-10 form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :original_filename, :class => 'col-md-2 control-label' %>
    <div class="col-md-10 form-text"><%= @scenario.original_filename %></div>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary btn-raised pull-right' %>
  </div>
<% end %>
</div>

app/views/scenarios/new.html.erb
<%= link_to '戻る', project_path(@scenario.project_id), :class => 'btn btn-default btn-raised' %>
<%= render_error_messages @scenario %>
<div class="well bs-component">
  <%= form_for([@project, @scenario], html: {class: 'form-horizontal'}) do |f| %>
    <%= f.hidden_field :project_id %>
  
    <div class="form-group">
      <%= f.label :name, :class => 'col-md-2 control-label' %>
      <%= f.text_field :name, :class => 'col-md-10 form-control' %>
    </div>
    <div class="form-group is-fileinput">
      <%= f.label :file, :class => 'col-md-2 control-label' %>
      <%= f.file_field :file, :class => 'col-md-10 form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit :class => 'btn btn-primary btn-raised pull-right' %>
    </div>
  <% end %>
</div>

app/views/scenarios/show.html.erb
<div class="page-header">
  <h3><%= @scenario.name %></h3>
</div>

<%= form_for([@scenario, BuildHistory.new], html: {class: 'build_history'}, remote: true) do |f| %>
  <%= f.submit 'テストを実行', class: 'btn btn-info btn-raised',style: 'display: inline-block;' %>
  <div class="checkbox" style= 'display: inline-block;'>
    <% devices.each do |device, checked| %>
      <%= label(:device, device) do %>
        <%= check_box_tag 'devices[]', device, checked,
                id:     "device_#{device}",
                class:  'form-control' %>
        <span class="checkbox-material">
          <span class="check"></span>
        </span>
        <%= device_icon(device) %>
        <%= device_title(device) %>
      <% end %>
    <% end %>
  </div>
  <hr/>
  <%= link_to '編集', edit_scenario_path(@scenario), :class => 'btn btn-info btn-raised xs-col-1' %>
  <%= link_to '削除', scenario_path(@scenario), :method => 'delete', :class => 'btn btn-danger btn-raised xs-col-1',
      :data => {:confirm => "#{@scenario.original_filename} を削除します。よろしいですか？"} %>
  <%= link_to 'ダウンロード', scenario_path(@scenario, format: :side), class: 'btn btn-default btn-raised xs-col-2', data: {turbolinks: false} %>
  <%= link_to '戻る', project_path(@scenario.project), :class => 'btn btn-default btn-raised xs-col-1' %>
<% end %>

<div class="scenario">
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table">
        <tr class="row">
          <th class="col-md-2">
            <%= Scenario.human_attribute_name :scenario_no %>
          </th>
          <td class="col-md-10">
            <%= @scenario.scenario_no %>
          </td>
        </tr>
        <tr class="row">
          <th class="col-md-2">
            <%= Scenario.human_attribute_name :original_filename %>
          </th>
          <td class="col-md-10">
            <%= @scenario.original_filename %>
          </td>
        </tr>
        <tr class="row">
          <th class="col-md-2">
            <%= Scenario.human_attribute_name :base_url %>
          </th>
          <td class="col-md-10">
            <%= @scenario.base_url %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="update-class-on-show-build-histories col-md-12">
      <div class="bs-component">
        <div id="steps">
          <%= render 'steps/index' %>
        </div>
      </div>
    </div>

    <div id="build-histories">
      <% if @scenario.build_histories.present? %>
        <%= render partial: "build_histories/index" %>
      <% end %>
    </div>
  </div>
</div>